import asyncio
import logging
import queue
from typing import Any

import orjson
from aiokafka import AIOKafkaProducer

from dynamic_des.connectors.egress.base import BaseEgress

logger = logging.getLogger(__name__)


class KafkaEgress(BaseEgress):
    """
    High-throughput Kafka producer for simulation telemetry and events.

    This connector utilizes `aiokafka` for asynchronous I/O and `orjson` for fast
    serialization. It implements a resilient connection loop with exponential
    backoff and handles two distinct data streams:
    1. Telemetry: Typically mapped to single-partition topics for system metrics.
    2. Events: Mapped to partitioned topics using event keys for ordering guarantees.

    Attributes:
        telemetry_topic (str): The Kafka topic name for telemetry data.
        event_topic (str): The Kafka topic name for lifecycle events.
        producer_config (dict): Configuration dictionary passed to AIOKafkaProducer,
            including performance optimizations like lz4 compression and batch lingering.
    """

    def __init__(
        self,
        telemetry_topic: str,
        event_topic: str,
        bootstrap_servers: str,
        **kwargs: Any,
    ):
        """
        Initializes the KafkaEgress with topic and connection settings.

        Args:
            telemetry_topic: Destination topic for telemetry stream.
            event_topic: Destination topic for event stream.
            bootstrap_servers: Comma-separated list of Kafka brokers.
            **kwargs: Additional overrides for the AIOKafkaProducer configuration.
        """
        self.telemetry_topic = telemetry_topic
        self.event_topic = event_topic

        # High-performance defaults for 100k/sec
        self.producer_config = {
            "bootstrap_servers": bootstrap_servers,
            "linger_ms": 10,  # Batch messages for 10ms before sending
            "compression_type": "lz4",  # Fast compression for high volume
            "max_batch_size": 131072,  # 128KB batch size
            **kwargs,
        }

    async def run(self, egress_queue: queue.Queue) -> None:
        """
        The main execution loop that consumes the egress queue and publishes to Kafka.

        This method maintains a persistent connection to Kafka. If the connection
        is lost, it implements an exponential backoff retry strategy. It polls
        the internal `egress_queue` for batches of data, determines the target
        topic based on the 'stream_type', and performs asynchronous sends.

        Args:
            egress_queue: A thread-safe queue containing lists of dictionaries
                (batches) generated by the EgressMixIn.

        Note:
            The loop exits gracefully upon receiving an `asyncio.CancelledError`,
            ensuring the Kafka producer is stopped correctly.
        """
        backoff = 1.0
        max_backoff = 60.0

        while True:
            try:
                producer = AIOKafkaProducer(**self.producer_config)
                await producer.start()
                logger.info("Kafka Egress producer connected successfully.")
                backoff = 1.0  # Reset backoff on successful connection

                try:
                    while True:
                        try:
                            # 'batch' is a list of dictionaries from the EgressMixIn
                            batch = egress_queue.get_nowait()

                            for data in batch:
                                stream = data.pop("stream_type")
                                if stream == "telemetry":
                                    topic = self.telemetry_topic
                                    key = (
                                        str(data["path_id"]).encode()
                                        if "key" in data
                                        else None
                                    )
                                else:
                                    topic = self.event_topic
                                    # Use the event_key for Kafka partitioning
                                    key = (
                                        str(data["key"]).encode()
                                        if "key" in data
                                        else None
                                    )

                                # orjson.dumps returns bytes directly (faster than json.dumps + encode)
                                await producer.send(
                                    topic, value=orjson.dumps(data), key=key
                                )

                        except queue.Empty:
                            # Yield to loop if queue is empty
                            await asyncio.sleep(0.001)
                finally:
                    await producer.stop()

            except asyncio.CancelledError:
                logger.info("Kafka Egress shut down requested. Exiting loop.")
                break
            except Exception as e:
                logger.error(
                    f"Kafka Egress connection failed: {e}. Retrying in {backoff} seconds..."
                )
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, max_backoff)
