import asyncio
import logging
import queue
from typing import Any

import orjson
import redis.asyncio as redis

from dynamic_des.connectors.egress.base import BaseEgress

logger = logging.getLogger(__name__)


class RedisEgress(BaseEgress):
    """
    High-throughput asynchronous egress provider for streaming simulation data to Redis.

    This connector utilizes `redis.asyncio` for asynchronous I/O and publishes batched
    simulation results (events and telemetry) to Redis Streams (`XADD`) for real-time consumers.

    By default, it uses a unified stream, but supports dynamic stream multiplexing
    by reading the `__stream__` key from the data payloads.

    Attributes:
        url (str): The connection URL for the Redis server (e.g., redis://localhost:6379/0).
        stream_name (str): The default target Redis Stream name.
        client (redis.Redis | None): The underlying redis-py asynchronous client instance.
        **kwargs: Additional configuration dictionary passed to `redis.from_url`.
    """

    def __init__(self, url: str, stream_name: str = "simulation_data", **kwargs: Any):
        """
        Initializes the RedisEgress with topic and connection settings.

        Args:
            url: Redis connection URL (e.g., redis://localhost:6379/0).
            stream_name: Target Redis Stream name.
            **kwargs: Additional arguments for `redis.from_url`.
        """
        self.url = url
        self.stream_name = stream_name
        self.kwargs = kwargs
        self.client: redis.Redis | None = None

    async def _init_client(self) -> None:
        if self.client is None:
            self.client = redis.from_url(self.url, **self.kwargs)
            logger.info(f"RedisEgress connected to stream '{self.stream_name}'")

    async def run(self, egress_queue: queue.Queue) -> None:
        """
        The main execution loop that consumes the egress queue and publishes to Redis.

        This method maintains a connection to Redis and uses pipeline (`XADD`)
        commands to insert batches of data efficiently.

        Args:
            egress_queue: A thread-safe queue containing lists of dictionaries
                or Pydantic models generated by the EgressMixIn.
        """
        await self._init_client()
        assert self.client is not None

        while True:
            try:
                batch = egress_queue.get_nowait()
                if not batch:
                    continue

                pipe = self.client.pipeline()
                count = 0
                for item in batch:
                    # Support multi-stream multiplexing
                    target = item.get("__stream__", self.stream_name)
                    item_copy = item.copy()
                    item_copy.pop("__stream__", None)

                    # Redis Streams expect a dict of string fields.
                    # We serialize the entire item into a single 'payload' field.
                    payload = orjson.dumps(item_copy).decode("utf-8")
                    pipe.xadd(target, {"payload": payload})
                    count += 1

                if count > 0:
                    await pipe.execute()
                logger.debug(f"Inserted {count} records into Redis Streams")

            except queue.Empty:
                await asyncio.sleep(0.1)
            except Exception as e:
                logger.error(f"Error publishing batch to Redis: {e}")
                await asyncio.sleep(1)
