site_name: Dynamic DES
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: purple
    - scheme: slate # Dark mode
      primary: teal
      accent: purple
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - API Reference: api.md
